"use client"
import Link from 'next/link'
import '../globals.css'
import { usePathname } from 'next/navigation';
const navs = [
  { id: 1, title: "Home", slug: '/' },
  { id: 2, title: "Shop", slug: '/shop' },
  { id: 3, title: "Products", slug: '/products' }
]
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  const pathname = usePathname();
  console.log(pathname);
  return (
    <html lang="en">
      <body>
        <div className='flex flex-col h-screen'>
          <header className='bg-slate-100 w-full p-3'>
            <ul className='flex gap-3'>
              {
                navs.map(nav => {
                  const isActive = pathname === nav.slug;
                  console.log(isActive);

                  return <li key={nav.id}><Link className={isActive ? "font-bold text-violet-400" : ''} href={nav.slug}>{nav.title}</Link></li>
                })
              }
            </ul>
          </header>
          <main className='flex-1 w-full p-3'>{children}</main>
          <footer className='bg-blue-100 w-full p-3'>User Root Layout Footer</footer>
        </div>
      </body>
    </html >
  )
}
